version: '3.8'
services:
  zookeeper:
    image: docker.io/confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports: 
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
  broker1:
    image: docker.io/confluentinc/cp-kafka:latest
    hostname: broker1
    container_name: broker1
    ports: 
      - 18092:18092
      - 19092:19092
      - 11192:11192
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:19092
      KAFKA_BROKER_ID: 1
      # KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1:19092,broker2:29092,broker3:39092
      CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: 'true'
      KAFKA_CONFLUENT_METADATA_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_CONFLUENT_METADATA_SERVER_LISTENERS: PLAINTEXT://:18092
      KAFKA_CONFLUENT_METADATA_SERVER_ADVERTISED_LISTENERS: PLAINTEXT://broker1:18092
    depends_on:
      zookeeper
  broker2:
    image: docker.io/confluentinc/cp-kafka:latest
    hostname: broker2
    container_name: broker2
    ports: 
      - 28092:28092
      - 29092:29092
      - 21192:21192
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:29092
      KAFKA_BROKER_ID: 2
      # KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1:19092,broker2:29092,broker3:39092
      CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: 'true'
      KAFKA_CONFLUENT_METADATA_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_CONFLUENT_METADATA_SERVER_LISTENERS: PLAINTEXT://:28092
      KAFKA_CONFLUENT_METADATA_SERVER_ADVERTISED_LISTENERS: PLAINTEXT://broker2:28092
    depends_on:
      zookeeper
  broker3:
    image: docker.io/confluentinc/cp-kafka:latest
    hostname: broker3
    container_name: broker3
    ports: 
      - 38092:38092
      - 39092:39092
      - 31192:31192
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:39092
      KAFKA_BROKER_ID: 3
      # KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1:19092,broker2:29092,broker3:39092
      CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: 'true'
      KAFKA_CONFLUENT_METADATA_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_CONFLUENT_METADATA_SERVER_LISTENERS: PLAINTEXT://:38092
      KAFKA_CONFLUENT_METADATA_SERVER_ADVERTISED_LISTENERS: PLAINTEXT://broker3:38092
    depends_on:
      zookeeper
  control-center:
    image: docker.io/confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    container_name: control-center
    ports:
      - 9021:9021
      - 9022:9022
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: PLAINTEXT://broker1:19092,PLAINTEXT://broker2:29092,PLAINTEXT://broker3:39092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_REPLICATION_FACTOR: 2
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 2
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_METRICS_TOPIC_REPLICATION: 2
      CONTROL_CENTER_METRICS_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_REST_LISTENERS: http://:9021,https://:9022
      CONFLUENT_METADATA_BOOTSTRAP_SERVER_URLS: PLAINTEXT://broker1:18092,PLAINTEXT://broker2:28092,PLAINTEXT://broker3:38092
      CONFLUENT_METADATA_BASIC_AUTH_USER_INFO: controlcenterAdmin:controlcenterAdmin
      PORT: 9021
    depends_on:
      broker1
      broker2
      broker3
      zookeeper
